# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: booking.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'booking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\"\x14\n\x06UserID\x12\n\n\x02id\x18\x01 \x01(\t\"*\n\x0b\x42ookingList\x12\x1b\n\x08\x62ookings\x18\x01 \x03(\x0b\x32\t._Booking\"7\n\x08_Booking\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x1d\n\tmovies_id\x18\x02 \x01(\x0b\x32\n.MovieList\"\x1e\n\tMovieList\x12\x11\n\tmovies_id\x18\x01 \x03(\t\"\x07\n\x05\x45mpty2w\n\x07\x42ooking\x12!\n\x07GetJson\x12\x06.Empty\x1a\x0c.BookingList\"\x00\x12&\n\x0bGetBookings\x12\x07.UserID\x1a\x0c.BookingList\"\x00\x12!\n\nAddBooking\x12\t._Booking\x1a\x06.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERID']._serialized_start=17
  _globals['_USERID']._serialized_end=37
  _globals['_BOOKINGLIST']._serialized_start=39
  _globals['_BOOKINGLIST']._serialized_end=81
  _globals['__BOOKING']._serialized_start=83
  _globals['__BOOKING']._serialized_end=138
  _globals['_MOVIELIST']._serialized_start=140
  _globals['_MOVIELIST']._serialized_end=170
  _globals['_EMPTY']._serialized_start=172
  _globals['_EMPTY']._serialized_end=179
  _globals['_BOOKING']._serialized_start=181
  _globals['_BOOKING']._serialized_end=300
# @@protoc_insertion_point(module_scope)
