# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: time.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'time.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntime.proto\"\x15\n\x07MovieID\x12\n\n\x02id\x18\x01 \x01(\t\"(\n\tMovieList\x12\x1b\n\tmovies_id\x18\x01 \x03(\x0b\x32\x08.MovieID\"\x14\n\x04\x44\x61te\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\">\n\x08TimeData\x12\x13\n\x04\x64\x61te\x18\x01 \x01(\x0b\x32\x05.Date\x12\x1d\n\tmovies_id\x18\x02 \x01(\x0b\x32\n.MovieList\"$\n\x08Schedule\x12\x18\n\x05times\x18\x01 \x03(\x0b\x32\t.TimeData\"\x07\n\x05\x45mpty2J\n\x04Time\x12\x1f\n\x08GetTimes\x12\x06.Empty\x1a\t.Schedule\"\x00\x12!\n\nShowMovies\x12\x05.Date\x1a\n.MovieList\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'time_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOVIEID']._serialized_start=14
  _globals['_MOVIEID']._serialized_end=35
  _globals['_MOVIELIST']._serialized_start=37
  _globals['_MOVIELIST']._serialized_end=77
  _globals['_DATE']._serialized_start=79
  _globals['_DATE']._serialized_end=99
  _globals['_TIMEDATA']._serialized_start=101
  _globals['_TIMEDATA']._serialized_end=163
  _globals['_SCHEDULE']._serialized_start=165
  _globals['_SCHEDULE']._serialized_end=201
  _globals['_EMPTY']._serialized_start=203
  _globals['_EMPTY']._serialized_end=210
  _globals['_TIME']._serialized_start=212
  _globals['_TIME']._serialized_end=286
# @@protoc_insertion_point(module_scope)
