openapi: 3.0.0
info:
  title: Movie Service API
  description: API for managing users and retrieving movie information.
  version: 1.0.0
servers:
  - url: http://localhost:3004
paths:
  /:
    get:
      summary: Welcome message
      description: Returns a welcome message for the Movie service.
      responses:
        '200':
          description: A welcome message
          content:
            text/html:
              schema:
                type: string

  /json:
    get:
      summary: Get all users
      description: Returns a JSON list of all users.
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: The user ID.
                    name:
                      type: string
                      description: The name of the user.
                    email:
                      type: string
                      description: The email of the user.

  /users/{userid}:
    get:
      summary: Get user by ID
      description: Retrieve a user by their unique ID.
      parameters:
        - name: userid
          in: path
          required: true
          description: The ID of the user to retrieve.
          schema:
            type: string
      responses:
        '200':
          description: A user object
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
        '400':
          description: User ID not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /adduser/{userid}:
    post:
      summary: Add a new user
      description: Adds a new user with the given ID.
      parameters:
        - name: userid
          in: path
          required: true
          description: The ID of the user to add.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                email:
                  type: string
      responses:
        '200':
          description: User added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '409':
          description: User ID already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /movie/{movieid}:
    get:
      summary: Get movie by ID
      description: Retrieve a movie by its unique ID.
      parameters:
        - name: movieid
          in: path
          required: true
          description: The ID of the movie to retrieve.
          schema:
            type: string
      responses:
        '200':
          description: A movie object
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  director:
                    type: string
                  rating:
                    type: number
                  actors:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        firstname:
                          type: string
                        lastname:
                          type: string
        '400':
          description: Error occurred during movie retrieval
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Failed to fetch movie data
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /movie/title/{title}:
    get:
      summary: Get movie by title
      description: Retrieve a movie by its title.
      parameters:
        - name: title
          in: path
          required: true
          description: The title of the movie to retrieve.
          schema:
            type: string
      responses:
        '200':
          description: A movie object
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  director:
                    type: string
                  rating:
                    type: number
                  actors:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        firstname:
                          type: string
                        lastname:
                          type: string
        '400':
          description: Error occurred during movie retrieval
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Failed to fetch movie data
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
